### ISSUE TITLE
Make page row count configurable

### ISSUE THREAD

**Issue by smithdtyler** [NASA-SW-VnV/fret#100]
FRET Version: 27.3.7
OS: Ubuntu 22

I'd like to be able to choose how many items to display in each table, rather than being limited to 10. 

![Screenshot 2024-12-11 at 3 24 04 PM](https://github.com/user-attachments/assets/e8d787d5-6a33-48ab-a7a8-dbcfdf0504a5)

**Comment by anmavrid** [comment]
Hi @smithdtyler,

You are not limited to 10. If you click on the down arrow next to the number 10, it will give you more options. See screenshot below.
<img width="524" alt="Screenshot 2024-12-11 at 1 36 39 PM" src="https://github.com/user-attachments/assets/754a08ec-356a-4bfe-b8e8-e27d1667ae9b" />

Is this helpful?

Thanks,
Anastasia

**Comment by smithdtyler** [comment]
Excellent, thanks @anmavrid!
