### ISSUE TITLE
Simulate option is unavailable even when realizability analysis with JKind Passes

### ISSUE THREAD

**Issue by smithdtyler** [NASA-SW-VnV/fret#102]
I analyzed the requirements for my Microwave project with JKind, but the option to simulate is still disabled. 

<img width="398" alt="Screenshot 2024-12-13 at 9 59 23 AM" src="https://github.com/user-attachments/assets/ceaa26dd-46ba-4e7b-abd9-a87fda3c36dc" />

<img width="631" alt="Screenshot 2024-12-13 at 9 59 17 AM" src="https://github.com/user-attachments/assets/15d04f15-acaf-4d9f-8548-1900407b8073" />

**Comment by andreaskatis** [comment]
Hi Tyler,

I will need a bit more information for this. Do you have NuSMV installed and if yes, are you able to access the simulator from the requirements editor? An easy way to see this is to open any requirement in the requirement editor, click on the `SEMANTICS` button, then see if the `SIMULATE` button is enabled in the bottom of the Assistant tab. I'm attaching a screenshot below.

![image](https://github.com/user-attachments/assets/9fad6468-9f62-4677-806f-e586ea0293bc)

**Comment by smithdtyler** [comment]
After installing NuSMV and LTLSIM, the Simulate button was in the requirement editor was enabled (see https://github.com/NASA-SW-VnV/fret/issues/103 for a recommendation for documentation regarding LTLSIM)

After confirming the simulate option in the requirement editor worked, I returned to the realization analysis tool. After switching to JKind and checking realizability, the simulate action was enabled. 

However, the tool tip was stale (see screenshot), I opened #104 accordingly. 

![Screenshot 2024-12-13 at 11 19 47 AM](https://github.com/user-attachments/assets/e90962ac-dc77-446e-b7f8-b973106792e9)

**Comment by smithdtyler** [comment]
After the help from @andreaskatis I am now able to run simulation. Thanks!
