### ISSUE TITLE
Unsuccessful Installation

### ISSUE THREAD

**Issue by Breeze822** [NASA-SW-VnV/fret#42]
Hello,
I got some unexpected error when I was trying to run an install of this application. My node version is 10.15.0, npm version is 6.4.1.
I have tried both "npm run fret-install" and "npm run fret-reinstall". But None of them works.

my Errol log and complete log  are as follows
[fret.log.txt](https://github.com/NASA-SW-Vn

[fret.log.txt](https://github.com/NASA-SW-VnV/fret/files/8954756/fret.log.txt)

[2022-06-22T05_33_05_434Z-debug.log](https://github.com/NASA-SW-VnV/fret/files/8954757/2022-06-22T05_33_05_434Z-debug.log)

Thanks

**Comment by anmavrid** [comment]
Hello @Breeze822,

We looked at your error log. 

By looking at these lines (in fret.log.txt)

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-64_binding.node":

connect ETIMEDOUT 20.205.243.166:443

Timed out whilst downloading the prebuilt binary 
```

it looks like there might be a problem with your network connection (or perhaps you are using a firewall that blocks the connection to the IP?).

**Comment by Breeze822** [comment]
Hello @anmavrid 
Thank you very much for your response. Just got a new VPN and solved that problem.
Yours sincerely,
Breeze

**Comment by anmavrid** [comment]
Great, @Breeze822!

I am closing this issue.

Anastasia
