### ISSUE TITLE
Export requirements status field in json format

### ISSUE THREAD

**Issue by ahmedwaqar** [NASA-SW-VnV/fret#44]
I looked at the exported JSON file and I see that the *status* field is not present.  I'd prefer to make the export feature more configurable with customizable fields to select in the export dialog. This would help the integration of FRET with other tools and also easy to filter requirements with approved status from those that are not.

**Comment by anmavrid** [comment]
Hi @ahmedwaqar,

thanks for your suggestions. We are currently working on extending the export/import functionality of FRET so this is good timing. 

Anastasia

**Comment by ahmedwaqar** [comment]
Thanks, @anmavrid. Are you considering exporting to CSV or .xlsx format in your upgrades?

**Comment by anmavrid** [comment]
Yes. We have added export to CSV format. It will be included in a future release.

**Comment by anmavrid** [comment]
This is included in release v3.0. I am closing the issue.
