### ISSUE TITLE
Realizability GUI issue

### ISSUE THREAD

**Issue by andreaskatis** [NASA-SW-VnV/fret#48]
Hello, the GUI of FRET on my centos become a white screen after I click the REALIZABILITY and nothing is outputed on the  terminal. Could you tell me what happen? Thanks.

_Originally posted by @kaci2002 in https://github.com/NASA-SW-VnV/fret/discussions/28#discussioncomment-4677592_

**Comment by andreaskatis** [comment]
Hi @kaci2002,

Thank you for reaching out. I do not believe that anyone in the team has tried FRET on CentOS. I haven't, so I am not sure how well the tool is supported in that particular distribution.

Regardless, I would still like to try and replicate your issue. For that, I will need more information.

1. Please specify the exact version of CentOS you are using.
2. Please describe exactly the actions that you take, that lead to the application crashing, starting from booting up FRET.
3. Have you created any projects in FRET? Any requirements in these projects? Have you used the "Variable Mapping" tab to any extent? If the answer is "yes" to any of these questions, please provide me with the corresponding information. For the requirements, please try to provide a minimal set that is still causing the issue.

Best Regards,

Andreas

**Comment by kaci2002** [comment]
Hi Andreas,

The version of CentOS is 7.9.2009.

These pictures show the actions I take that lead to the appilcation crashing.
![屏幕截图 2023-01-14 121224](https://user-images.githubusercontent.com/121812894/212450265-58e988ea-52c8-4c3b-ae96-6c5f58ce287e.png)
![屏幕截图 2023-01-14 121356](https://user-images.githubusercontent.com/121812894/212450269-d5120bda-660b-4214-b690-9aa8fd39ce8a.png)
![屏幕截图 2023-01-14 121427](https://user-images.githubusercontent.com/121812894/212450270-51a07632-1424-47e5-bd38-52312b1df046.png)
![屏幕截图 2023-01-14 121443](https://user-images.githubusercontent.com/121812894/212450271-2e96a655-c79c-46a2-be73-2c27f41180c7.png)

I have imported the project in $PATH_TO_FRET/fret/tutorialExamples/FRETDemo.json.

The "Variable Mapping" tab can be used normally but I hacen't used it.

Thanks.
kaci2002

**Comment by andreaskatis** [comment]
Hi @kaci2002 ,

I went ahead and installed FRET (current version of our `master` branch) on a Centos 7.9.2009 VM image. Unfortunately, I have not been able to replicate your issue. Importing the file and following the action steps in your screenshots did not lead to a crash on my copy.

This looks like an isolated issue, depending on something else that you may have changed while interacting with the tool. Here are some more questions: 

1. Are you using the latest version of `master`? 
2. Have you maybe modified any of the requirements in the "Demo-FSM" project, in any way? 
3. Since you are trying to use realizability, I suppose that you've tried to install the dependencies that are needed for it. If so, which ones have you installed? Did you add them to your PATH environment variable? When calling the tools from the command line, what is their output?

The only other thing I could suggest is maybe trying to run FRET in developer mode by running `npm run dev` instead of `npm start`. Then, repeat the offending actions and see whether any error messages pop up in the Console Tab under the developer tools window (which should appear to the right of the main FRET window when running in developer mode). If you see any, please forward them to us.

Best Regards,

Andreas

**Comment by andreaskatis** [comment]
Hi @kaci2002,

Have you been able to solve your issue with your CentOS installation? 

Best Regards,

Andreas

**Comment by andreaskatis** [comment]
Hi @kaci2002 ,

I am closing this issue, since I have not received any further updates on your behalf. If you do, feel free to add a new comment to this thread.

Best Regards,

Andreas
