### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by zutshi** [NASA-SW-VnV/fret#49]
The 7th link [Using the simulator](https://github.com/NASA-SW-VnV/fret/blob/v2.0/fret-electron/docs/_media/usingTheSimulator/ltlsim.md) in the user manual is broken -- https://github.com/NASA-SW-VnV/fret/blob/v2.0/fret-electron/docs/_media/userManual.md

It should probably be pointing to https://github.com/NASA-SW-VnV/fret/blob/v2.0/fret-electron/docs/_media/UsingTheSimulator/ltlsim.md

**Comment by anmavrid** [comment]
@zutshi,

Thank you for your interest in FRET!

The link that you used is from FRET v2.0. This has been fixed since then. Here is the latest code for the manual (v2.6): https://github.com/NASA-SW-VnV/fret/blob/master/fret-electron/docs/_media/userManual.md 

Thank you,
Anastasia

**Comment by zutshi** [comment]
Thanks!
