### ISSUE TITLE
Error on Install: regex.h no such file or directory

### ISSUE THREAD

**Issue by jakeweidokal** [NASA-SW-VnV/fret#50]
Hello,

When trying to install fret, I receive errors that appear to be due to `gcc` not being able to find the `regex.h` file.

I am running:
- Windows 10
- Node 16.14.1
- NPM 9.3.1
- NuSMV 2.6.0
- GNU Make 4.3
- gcc 12.2.0

When running `npm run fret-install` I receive the following error (full log [here](https://github.com/NASA-SW-VnV/fret/files/10573320/2023-02-02T20_30_11_021Z-debug-0.log))

```
$ npm run fret-install



> fret@0.0.1 fret-install
> npm --prefix ../tools/LTLSIM/ltlsim-core install ../tools/LTLSIM/ltlsim-core && npm install

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\jweidoka\fret\tools\LTLSIM\ltlsim-core\node_modules\tools\LTLSIM\ltlsim-core/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\jweidoka\fret\tools\LTLSIM\ltlsim-core\node_modules\tools\LTLSIM\ltlsim-core\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jweidoka\AppData\Local\npm-cache\_logs\2023-02-02T20_30_11_021Z-debug-0.log

```

To try to get to the root of this, I did an `npm install` inside of the `fret/tools/LTLSIM/ltlsim-core` directory and got the following error (full log [here](https://github.com/NASA-SW-VnV/fret/files/10573304/2023-02-02T20_32_08_586Z-debug-0.log))

```
MINGW64 ~/fret/tools/LTLSIM/ltlsim-core (master)
$ npm install

> ltlsim-core@1.0.0 install
> make -C "./simulator" && make -C "./simulator" clean

make: Entering directory 'C:/Users/jweidoka/fret/tools/LTLSIM/ltlsim-core/simulator'
gcc -c -o ltlsim_commands.o ltlsim_commands.c -I. -g -Wall -DWINDOWS
In file included from ltlsim_commands.c:1:
ltlsim_commands.h:10:10: fatal error: regex.h: No such file or directory
   10 | #include <regex.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:25: ltlsim_commands.o] Error 1
make: Leaving directory 'C:/Users/jweidoka/fret/tools/LTLSIM/ltlsim-core/simulator'
npm ERR! code 2
npm ERR! path C:\Users\jweidoka\fret\tools\LTLSIM\ltlsim-core
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c make -C "./simulator" && make -C "./simulator" clean

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jweidoka\AppData\Local\npm-cache\_logs\2023-02-02T20_32_08_586Z-debug-0.log

```

I am not very familiar with compiling C code, is there something else I need to install to make the regex.h file available? Or would this be caused by something else?

Any help you can provide is greatly appreciated!

**Comment by andreaskatis** [comment]
Hi @jakeweidokal ,

The current installation script on 'master'  does not work properly on Windows machines. We are currently working on a fix which will appear in the next release.

In general, to run FRET on Windows, you need to install Cygwin (this is the solution that we have had the most success with so far). A detailed guide can be seen in the end of this post (we will add this back to our main guide with the new release)

Please disregard the note in the guide that recommends node v10.15.0, but make sure that the current version of node that you have installed is actually accessible via the Cygwin terminal.

**IMPORTANT NOTE:** Before the step in the guide that asks you to run 'npm run fret-install', you would need to do the following:

1. 'cd fret/fret-electron'
2. 'npm uninstall babel-register'
3. 'npm uninstall babel-core'
4. 'npm install @babel/core @babel/register --save-dev'

These steps will not be necessary with the future release.

After the above commands are completed, follow the rest of the guide. If you encounter an error during the end of the installation that mentions webpack not supporting native dependencies, please disregard.

The guide can be found here:

https://github.com/NASA-SW-VnV/fret/blob/fretExecutables/fret-electron/docs/installation_windows.md

If you have further questions, please let us know!

**Comment by jakeweidokal** [comment]
This resolved my issue. Thank you for the detailed answer!

**Comment by anmavrid** [comment]
Thanks everyone. I am closing this issue.
