### ISSUE TITLE
Bug: All Caps "Immediately" keyword causes blank screen

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#56]
If I type IMMEDIATELY as the timing keyword (as opposed to "immediately") I get a blank screen and a bunch of TypeErrors if the dev log is running.

I found this while using Mu-FRET, but tested it in FRET (in a version pulled today from the FRET repo).

The brief original issue is in our Mu-FRET repo: [https://github.com/valu3s-mu/mu-fret/issues/25](https://github.com/valu3s-mu/mu-fret/issues/25) but the error doesn't depend on it being a new requirement like I though initially.

**Steps**
1. In the Edit Requirement dialogue add/edit the fretish text to include the timing keyword "IMMEDIATELY" (in all caps)
2. Press "Semantics"
3. See the blank screen.

**Comment by anmavrid** [comment]
Thank you, Matt. We are looking into that.

**Comment by mluckcuck** [comment]
No problem.

Sorry, I forgot to mention the system specs.

I'm running Ubuntu 20.04.6, node is version 14.19.1 and npm is version 6.14.16 ... if any of that is relevant!

**Comment by tpressburger** [comment]
We have fixed the problem in the new release which will be available soon. Thanks for finding the problem!

**Comment by anmavrid** [comment]
I am closing this issue.
