### ISSUE TITLE
Requirement Description Text Box Stops Various Keys (and highlighting) from Working

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#63]
When typing in the Requirements Description text box, various keys do not work. 
E.G.:
- Home
- End
- CTRL+SHIFT+left arrow (should accumulate highlight, but it only highlights a word/part and then loses the highlight to highlight the next word/part)

Also, trying to highlight with the mouse (click and drag) only works from the front (first word) to the back (last word) of the string. If I try to highlight from the end of the string, going towards the front I get the same problem as with trying to highlight using CTRL+SHIFT+left arrow .

This is v3.0, running on Ubuntu 20.04.6.

**Comment by anmavrid** [comment]
Thank you @mluckcuck. We are working on this.

**Comment by anmavrid** [comment]
These enhancements have been added in the requirement editor and the highlighting issue has been fixed. Everything will be available in the next FRET release.

**Comment by mluckcuck** [comment]
> These enhancements have been added in the requirement editor and the highlighting issue has been fixed. Everything will be available in the next FRET release.

Thanks @anmavrid :)

**Comment by anmavrid** [comment]
These enhancements and fixes are available now. See [release notes](https://github.com/NASA-SW-VnV/fret/releases/tag/v2.9.0) for more info.

I am closing this issue.
