### ISSUE TITLE
Trailing bit of requirement after a colon

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#64]
Hi

If I have a variable name with a colon ":" in it (in this case the variable was a ratio) FRET will save it ok and say that it's fomalised, but checking the Temporal Logic output shows that anything after the colon is lost. 

The only hint to this in FRET is that the text after the colon is not highlighted, but that's a very subtle hint that it's ignoring the remainder of the requirement. It would be nice if this still showed in the UI as an error.

**Comment by anmavrid** [comment]
Hi @mluckcuck,

colon is not supported in a variable name. If you use colon in a variable used in the condition or scope fields, the parser returns an error (see screenshot below). In the response field it turns the text after the colon black (meaning that it is not parsing). We will also add an error message.

If you want to use colon in a variable name (or any character that is not supported by the ID grammar field), you can write the variable name within quotes, e.g., "p:2" 

Thanks,

Anastasia

<img width="623" alt="Screen Shot 2023-11-21 at 4 08 02 PM" src="https://github.com/NASA-SW-VnV/fret/assets/25355219/e586df9c-0cd5-471a-9f69-22e10f5223de">

**Comment by anmavrid** [comment]
This enhancement has been added and it will be part of the next FRET release. 

Thank you @mluckcuck. Stay tuned!
