### ISSUE TITLE
Search Bar Doesn't Respond to Enter Key

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#65]
Hi,

I really like the new search bar, but for me it doesn't respond to the Enter key to search. Instead, I have to click the magnifying glass icon. This is a minor inconvenience but happens a lot!

This happens with  v3.0, running on Ubuntu 20.04.6

**Comment by anmavrid** [comment]
Hi Matt,

Thanks for your feedback. Actually, it is not designed to work with the Enter key. To search, you always need to click on the icon.

I will discuss with the FRET team about that.

Thanks,
Anastasia

**Comment by mluckcuck** [comment]
> Thanks for your feedback. Actually, it is not designed to work with the Enter key. To search, you always need to click on the icon.
> 
> I will discuss with the FRET team about that.

Thanks Anastasia. 
I think it would be useful to have the search bar respond to the enter key, it's what I would expect a search bar to do. Seems like a usual HCI approach to me.

Sorry to add something else, but another thing I've noticed that doesn't feel externally consistent is that if I search for some text, then press the clear button (the X next to the search box) I expect it to go back to the full list of requirements in that project. Instead I have to click the each button again, 'searching' for nothing to get it to show me everything. This feels odd and is another mouse click to get back to where I want to be.

**Comment by anmavrid** [comment]
We have added that! It will be available in the next release.

Thank you,
Anastasia
