### ISSUE TITLE
Missing FRET Version Number

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#90]
Both package.json files show the version number as 0.0.1. As far as I can remember it's been this way for years.
Obviously this isn't a 'show stopper' but it makes it very hard to work out which version of FRET I have downloaded, or which version it causing a particular problem.

(Purley selfishly, its also hard to keep track of the upstream changes that have/haven't been merged into our fork.)

**Comment by anmavrid** [comment]
Great point, @mluckcuck! Thanks.

To synch with our internal repo, we will update the version number in the upcoming release.

**Comment by anmavrid** [comment]
FRET version added in package.json for v2.9.1.

**Comment by mluckcuck** [comment]
Great! Thanks @anmavrid  this should make things much easier.
