### ISSUE TITLE
New Templates Only Available in Dev Mode

### ISSUE THREAD

**Issue by mluckcuck** [NASA-SW-VnV/fret#94]
Hi, I've got a weird problem here.

I have developed some new templates, for a paper, and I've been able to incorporate them into other FRET installations easily. But using the FRET installation I have on my work desktop machine, I can only see the templates if I use `npm run dev` to start FRET. 

I can't see anything in the dev console that seems to mention the templates, so I don't know why this works. But if I use `npm start` the templates list only contains the templates from basicTemplates.js; if I use `npm run dev` then my new templates appear in the list as well.

Any ideas why this might be?

Thanks

**Comment by anmavrid** [comment]
Hi Matt,

We are investigating this. Thanks for letting us know.

**Comment by anmavrid** [comment]
Hi Matt,

In a recent release, we separated the build process from `npm start`. If you're updating the FRET code, such as adding new templates, you'll need to build before starting.

To make this easier, we've added the bstart command, which combines both steps. Simply do `npm run bstart` whenever you've made changes and want to start FRET. After the initial build, if no further code or template changes are made, you can continue using `npm start` as usual.

This is documented in the FRET [developer's guide](https://github.com/NASA-SW-VnV/fret/blob/master/fret-electron/docs/_media/developersGuide/installingAndRunningFRET.md).

Hope this helps!

Anastasia

**Comment by mluckcuck** [comment]
Thanks for this. I thought this would be a much more difficult problem to solve!

I'm just wondering: why did this cause a problem with the templates? I had assumed that the templates.json file was just read at start-up; is it only read during the build?
